// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';

// Legacy URL redirects (generated by migration script)
import { legacyRedirects } from './src/data/redirects.ts';

// https://astro.build/config
export default defineConfig({
  site: 'https://www.rockoder.com',
  output: 'static',
  integrations: [
    react(),
    sitemap(),
  ],
  vite: {
    plugins: [tailwindcss()],
  },
  markdown: {
    shikiConfig: {
      theme: 'github-dark',
      wrap: true,
    },
  },
  redirects: {
    ...legacyRedirects,
  },
});
